# Generated by Django 3.0.8 on 2020-07-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_app', '0002_remove_puzzle_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='description',
            field=models.CharField(default='description', max_length=50),
            preserve_default=False,
        ),
    ]
